services:
  backend:
    build: 
      context: .
      target: development
    container_name: sooneats_backend_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && node node_modules/@nestjs/cli/bin/nest.js start --watch"
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: sooneats_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3378:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: